import type { DeliveryAddress } from "./delivery-address";
export type Product = {
  return_eligible?: boolean;
  loose_stock?: number;
  cost_net_cents?: number | null;
  stock_version?: number;
  revision?: number;
  group_name?: string;
  variant?: string;
  image_url?: string;
  image_source?: string;
  deposit_profile?: string;
  data_note?: string;
  id: string;
  sku: string;
  name: string;
  category: string;
  pack_count: number;
  volume_ml: number;
  price_cents: number;
  source_unit_price_cents: number | null;
  deposit_cents: number | null;
  tax_rate: number;
  deposit_tax_rate: number;
  stock: number | null;
  min_stock: number;
  target_stock: number;
  supplier_id: string | null;
  reorder_enabled: boolean;
  active: boolean;
  verified: boolean;
  barcode: string;
  source: string;
  kind: string;
};
export type Supplier = {
  id: string;
  name: string;
  email: string;
  phone: string;
  number?: number;
  company?: string;
  address?: string;
  contact?: string;
  notes?: string;
  is_demo: boolean;
  auto_send: boolean;
};
export type CartLine = { product: Product; quantity: number };
export type Order = Partial<DeliveryAddress> & {
  requested_payment_method?: "cash" | "card" | "invoice" | null;
  approved_payment_method?: "cash" | "card" | "invoice" | null;
  payment_revision?: number;
  requested_delivery_date?: string | null;
  subscription_id?: string | null;
  recurrence_date?: string | null;
  created_by?: string | null;
  customer_id?: string | null;
  delivery_date?: string | null;
  eta_start?: string | null;
  eta_end?: string | null;
  route_position?: number | null;
  delivered?: Record<string, number>;
  preference_snapshot?: {
    windows?: { day: number; from: string; to: string }[];
    dropoff_allowed?: boolean;
    dropoff_note?: string;
    latitude?: number | null;
    longitude?: number | null;
  };
  id: string;
  number: number;
  customer_name: string;
  email: string;
  phone: string;
  address: string;
  notes: string;
  items: {
    id: string;
    tax_rate?: number;
    deposit_tax_rate?: number;
    name: string;
    quantity: number;
    price_cents: number;
    deposit_cents: number | null;
  }[];
  status: string;
  created_at: string;
};
export type ReceiptIssuer = {
  business_name: string;
  business_address: string;
  tax_number: string;
  vat_id: string;
  register_id: string;
  website: string;
};
export type FiscalReceipt = {
  transaction_number: string;
  started_at: string;
  finished_at: string;
  register_serial: string;
  tse_serial: string;
  signature: string;
  signature_counter: string;
};
export type Sale = {
  record_type?: "sale" | "cancellation" | "return";
  original_sale_id?: string | null;
  original_number?: number | null;
  reversal_reason?: string;
  reversal_note?: string;
  issuer_snapshot?: ReceiptIssuer | null;
  fiscal?: FiscalReceipt | null;
  actor_name?: string;
  id: string;
  number: number;
  created_at: string;
  items: SaleLine[];
  total_cents: number;
  net_cents: number;
  tax_cents: number;
  deposit_cents: number;
  payment: string;
  test_mode: boolean;
};
export type SaleLine = {
  return_eligible?: boolean;
  original_line?: number;
  net_cents?: number;
  deposit_net_cents?: number;
  restock?: boolean;
  original_price_cents?: number;
  discount_percent?: number;
  discount_reason?: string;
  discount_scope?: "cart" | "item" | "none";
  id: string;
  name: string;
  quantity: number;
  price_cents: number;
  deposit_cents: number;
  tax_rate: number;
  deposit_tax_rate: number;
};
export type Purchase = {
  dispatch?: {
    status: string;
    error: string | null;
    sent_at: string | null;
  } | null;
  source: "automatic" | "manual";
  created_by?: string | null;
  requested_date?: string | null;
  reference?: string;
  notes?: string;
  dispatch_method?: "email" | "external" | null;
  id: string;
  supplier_id: string;
  status: string;
  items: {
    id: string;
    name: string;
    quantity: number;
    sku?: string;
    pack_count?: number;
    volume_ml?: number;
  }[];
  created_at: string;
};
export type Settings = {
  business_street?: string;
  business_house_number?: string;
  business_postal_code?: string;
  business_city?: string;
  live_mode?: boolean;
  guest_orders?: boolean;
  reorder_days?: number[];
  reorder_time?: string;
  reorder_weeks?: number;
  reorder_anchor?: string;
  delivery_days?: number[];
  delivery_from?: string;
  delivery_to?: string;
  delivery_stop_minutes?: number;
  tax_number?: string;
  vat_id?: string;
  register_id?: string;
  default_tax_rate?: number;
  default_deposit_tax_rate?: number;
  business_name?: string;
  business_address?: string;
  discount_percent?: number;
  route_geocoding?: boolean;
  auto_reorder: boolean;
  instagram: string;
  domain: string;
  printer_mode: string;
  printer_address: string;
  printer_model?: string;
  printer_device_id?: string;
  printer_width_dots?: 512 | 576;
  tse_provider: string;
  smtp_enabled: boolean;
  smtp_host: string;
  smtp_port: number;
  smtp_user: string;
  smtp_from: string;
  smtp_password_set?: boolean;
  invoice_payment_days?: number;
  invoice_reminders_enabled?: boolean;
};
export type Customer = Partial<DeliveryAddress> & {
  payment_method?: "cash" | "card" | "invoice";
  online_account?: {
    user_id: string | null;
    email: string | null;
    confirmed: boolean;
    has_password: boolean;
  };
  id: string;
  number: number;
  user_id: string | null;
  name: string;
  email: string;
  phone: string;
  address: string;
  notes: string;
  invoice_email: boolean;
  dropoff_allowed: boolean;
  dropoff_note: string;
  windows: { day: number; from: string; to: string }[];
  latitude: number | null;
  longitude: number | null;
  created_at: string;
};
export type Employee = {
  finance_readonly?: boolean;
  user_id: string;
  number: number;
  name: string;
  email: string;
  phone: string;
  address: string;
  notes: string;
  role: string;
  active: boolean;
  permissions: string[];
  has_pin: boolean;
};
export type Delivery = {
  deposit_returns?: SaleLine[];
  total_cents?: number | null;
  payment_method?: "cash" | "card" | "invoice" | null;
  id: string;
  number: number;
  order_id: string;
  customer_id: string | null;
  items: SaleLine[];
  status: string;
  signature: string | null;
  signed_name: string;
  delivered_at: string | null;
  created_at: string;
  revision: number;
  mode: string;
};
export type Invoice = {
  payment_method?: "cash" | "card" | "invoice";
  payment_terms_days?: number | null;
  due_date?: string | null;
  paid_at?: string | null;
  reminder_stage?: number;
  reminder_status?: string;
  payment_entry?: InvoicePayment | null;
  id: string;
  number: number;
  order_id: string;
  delivery_id: string;
  customer_id: string | null;
  items: SaleLine[];
  customer_snapshot: { name: string; email: string; address: string };
  total_cents: number;
  net_cents: number;
  tax_cents: number;
  deposit_cents: number;
  status: string;
  mode: string;
  created_at: string;
};
export type Subscription = {
  revision: number;
  notes: string;
  last_error: string | null;
  id: string;
  customer_id: string;
  items: { id: string; quantity: number }[];
  interval: string;
  next_date: string;
  active: boolean;
};

export type InvoicePayment = {
  id: string;
  invoice_id: string;
  amount_cents: number;
  method: "cash" | "card" | "bank";
  paid_at: string;
  actor: string;
  source: "delivery" | "manual";
  created_at: string;
};
